// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionItem = { id: string, group_id: string, title: string, body: string, assignee_id: string, planned_start: string | null, status: string, created_by: string, created_at: string, updated_at: string, revision: number, run_id: string | null, error: string | null, };
