// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Workspace } from "./Workspace";

export type Agent = { id: string, project_id: string | null, name: string, position: string, role: string, reports_to: string | null, color: string, model: string, reasoning: string, instructions: string, agents_md: string, workdir: Workspace | null, permission: string, timeout_seconds: number, enabled: boolean, deleted_at: string | null, revision: number, };
