// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Artifact = { id: string, group_id: string, name: string, media_type: string, size: number, sha256: string, status: string, error: string | null, created_at: string, };
