// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelOption } from "./ModelOption";

export type CodexSettings = { model: string, reasoning: string, models: Array<ModelOption>, fetched_at: string | null, };
