// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Connection = { host: string, status: string, checked_at: string, message: string, version: string, os: string, environment_keys: Array<string>, };
