// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Folder } from "./Folder";

export type DirectoryView = { path: string, parent: string | null, roots: Array<Folder>, folders: Array<Folder>, };
