// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupSection } from "./GroupSection";
import type { GroupSort } from "./GroupSort";

export type GroupPreferences = { sort: GroupSort, pinned: Array<string>, order: Array<string>, sections: Array<GroupSection>, collapsed: Array<string>, };
