// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupAccess = { levels: Array<number> | null, participant_ids: Array<string>, delegate_ids: Array<string>, chat_lead_id: string | null, };
