// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";

export type Group = { id: string, name: string, description: string, project: Project | null, scope_levels: Array<number> | null, chat_lead_id: string | null, archived_at: string | null, deleted_at: string | null, };
