// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageReport } from "./UsageReport";

export type Message = { id: string, group_id: string, side_chat_id: string | null, sender: string, body: string, recipients: Array<string>, reply_to: string | null, artifacts: Array<string>, run_id: string | null, created_at: string, auto_routed: boolean, schedule_id: string | null, command: string | null, usage_report: UsageReport | null, };
