// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningOption } from "./ReasoningOption";

export type ModelOption = { slug: string, display_name: string, visibility: string, default_reasoning_level: string, supported_reasoning_levels: Array<ReasoningOption>, };
