// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupAccess } from "./GroupAccess";
import type { OrganizationMember } from "./OrganizationMember";
import type { Project } from "./Project";

export type OrganizationContext = { project: Project | null, group_access: GroupAccess | null, captured_at: string, owner_name: string, agent_id: string, chat_lead_id: string | null, manager_id: string, reporting_chain: Array<string>, direct_report_ids: Array<string>, team_member_ids: Array<string>, peer_ids: Array<string>, assigned_by_id: string, return_results_to_id: string, members: Array<OrganizationMember>, };
