// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrganizationMember = { id: string, name: string, position: string, role: string, reports_to: string, enabled: boolean, workdir: string | null, permission: string, environment_keys: Array<string>, available: boolean, unavailable_reason: string | null, };
