// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectMember } from "./ProjectMember";
import type { Workspace } from "./Workspace";

export type Project = { workdir: Workspace, members: Array<ProjectMember>, };
