// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Answer } from "./Answer";
import type { Question } from "./Question";

export type QuestionRequest = { id: string, request_id: string, run_id: string, agent_id: string, agent_name: string, group_id: string, side_chat_id: string | null, questions: Array<Question>, answers: { [key in string]?: Answer }, status: string, delivered: boolean, created_at: string, answered_at: string | null, error: string | null, };
