// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent } from "./Agent";
import type { OrganizationContext } from "./OrganizationContext";
import type { RunKind } from "./RunKind";
import type { JsonValue } from "./serde_json/JsonValue";

export type Run = { id: string, group_id: string, message_id: string, side_chat_id: string | null, agent_id: string, session_id: string, native_session_id: string | null, status: string, cwd: string, profile: Agent, created_at: string, started_at: string | null, ended_at: string | null, pid: number | null, remote_pid: number | null, exit_code: number | null, error: string | null, output: string, executable: string, arguments: Array<string>, model_display_name: string | null, usage: JsonValue | null, kind: RunKind, parent_run_id: string | null, task: string | null, organization_context: OrganizationContext | null, };
