// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Schedule = { id: string, group_id: string, name: string, body: string, start_at: string, repeat_minutes: number | null, next_run_at: string | null, enabled: boolean, last_sent_at: string | null, last_message_id: string | null, last_error: string | null, };
