// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Skill } from "./Skill";
import type { SkillError } from "./SkillError";

export type SkillList = { cwd: string, skills: Array<Skill>, errors: Array<SkillError>, text: string | null, };
