// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Skill = { name: string, description: string, path: string, scope: string, enabled: boolean, };
