// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalRun = { id: string, agent_id: string, command: string, cwd: string, canonical_cwd: string, shell: string, status: string, output: string, created_at: string, ended_at: string | null, exit_code: number | null, error: string | null, };
