// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageBucket } from "./UsageBucket";

export type UsageReport = { checked_at: string, buckets: Array<UsageBucket>, opencode_usage: string | null, };
