// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageWindow } from "./UsageWindow";

export type UsageBucket = { limitId: string | null, limitName: string | null, planType: string | null, primary: UsageWindow | null, secondary: UsageWindow | null, };
