// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Workstation = { id: string, name: string, hostname: string, host_ip: string, port: number, username: string, auth: string, ssh_alias: string, ssh_key_path: string, secret_saved: boolean, };
