// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Workspace = { ssh_host: string | null, path: string, canonical_path: string, git_root: string | null, };
