[workspace]
resolver = "3"
members = ["backend", "vendor/cccc-windows-process"]
default-members = ["backend"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.94"

[workspace.dependencies]
windows-sys = "0.61"

[profile.dev]
debug = 0

[profile.release]
debug = 0
strip = "debuginfo"
