import assert from "node:assert/strict";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { expect } from "@playwright/test";

export async function verifyGroupScope({ page, request, call, state, until, finished, org, base, directory }) {
  assert(process.env.AE_TEST_ORG && path.resolve(org) !== path.resolve("../../org"), "Use a disposable organization");
  page.setDefaultTimeout(20000);
  const catalog = await call("/codex/settings", undefined, "GET");
  const model = catalog.models.find((entry) => entry.slug === "gpt-5.6-luna")?.slug ?? catalog.model;
  const folder = async (name) => {
    const location = path.join(org, "codebases", name);
    await mkdir(location, { recursive: true });
    execFileSync("git", ["init", location], { stdio: "ignore" });
    return (await call("/workspaces/probe", { path: location })).workspace;
  };
  const leadDir = await folder("board");
  const workerDir = await folder("analyst");
  const marker = `DELEGATE_EVIDENCE_${crypto.randomUUID()}`;
  const evidence = path.join(workerDir.path, "evidence.txt");
  await writeFile(evidence, marker);
  let leader = (await state()).agents.find((agent) => agent.id === "ceo");
  leader = await call("/agents/ceo", { ...leader, name: "Board Chair", position: "Chief Executive Officer (CEO)", workdir: leadDir, model, reasoning: "low", timeout_seconds: 300, instructions: "Follow the current task and group_access permissions exactly. Delegate only when requested; never invent completion. For delegate-worker-evidence, assign only the requested file read and the check of the worker's Recent group conversation array. Do not include earlier chat messages in that assignment. Summarize returned evidence for the owner." }, "PUT");
  const manager = await call("/agents", { ...leader, id: "", name: "Director", position: "Data Director", reports_to: leader.id, workdir: workerDir });
  let worker = await call("/agents", { ...leader, id: "", name: "Analyst", position: "Research Analyst", reports_to: manager.id, workdir: workerDir, instructions: "Complete the assigned file read. Include the exact marker you read. If the Recent group conversation array supplied by the platform is empty, also include HISTORY_EMPTY. Return your evidence to the assigning agent without addressing the group. Never delegate." });
  await page.getByRole("button", { name: "Add group or section", exact: true }).click();
  await page.getByRole("menuitem", { name: "Create group", exact: true }).click();
  let dialog = page.getByRole("dialog", { name: "Create a group" });
  await dialog.getByLabel("Name", { exact: true }).fill("Board scope verification");
  await dialog.getByLabel("Who can join the chat").selectOption("levels");
  await expect(dialog.getByRole("checkbox", { name: "Level 1", exact: true })).toBeChecked();
  await expect(dialog.getByLabel("Group scope preview")).toContainText("1 chat participant");
  await expect(dialog.getByLabel("Group scope preview")).toContainText("2 lower-level agents");
  await dialog.getByLabel("Group chat lead").selectOption(leader.id);
  await dialog.getByRole("button", { name: "Save group", exact: true }).click();
  await expect(dialog).toBeHidden();
  let group = (await state()).groups.find((entry) => entry.name === "Board scope verification");
  const groupUrl = page.url();
  const access = async () => (await state()).group_access[group.id];
  const messages = () => call(`/groups/${group.id}/messages`, undefined, "GET");
  const send = (body, recipients = []) => call("/messages", { id: crypto.randomUUID(), group_id: group.id, body, recipients });
  assert.deepEqual((await access()).participant_ids, [leader.id]);
  assert((await access()).delegate_ids.includes(worker.id));
  assert.equal((await state()).groups.find((entry) => entry.id === "general").scope_levels, null);
  await page.getByRole("button", { name: "View group agents" }).click();
  await expect(page.getByRole("list", { name: "Group agents" }).getByText("Analyst", { exact: true })).toHaveCount(0);
  await page.getByRole("dialog").getByRole("button", { name: "Close", exact: true }).click();
  for (const scope_levels of [[], [0], [1, 1]]) {
    assert.equal((await request.post("/api/groups", { data: { ...group, scope_levels } })).status(), 400);
  }
  assert.equal((await request.post("/api/groups", { data: { ...group, chat_lead_id: worker.id } })).status(), 400);
  const before = await messages();
  assert.equal((await request.post("/api/messages", { data: { id: crypto.randomUUID(), group_id: group.id, body: "Forbidden direct message", recipients: [leader.id, worker.id] } })).status(), 400);
  assert.deepEqual(await messages(), before);
  const anonymous = await page.context().browser().newContext({ baseURL: base });
  assert.equal((await anonymous.request.post("/api/groups", { data: group })).status(), 401);
  await anonymous.close();
  const input = page.getByRole("textbox", { name: "Message", exact: true });
  await input.fill(`@${worker.id} This direct mention is outside the group's chat scope.`);
  await page.getByRole("button", { name: "Send message", exact: true }).click();
  await expect(page.getByRole("alert")).toContainText("outside this group's chat scope");
  await input.fill("@all Reply exactly BOARD_ONLY_HISTORY. Do not use tools or delegate.");
  await page.getByRole("button", { name: "Send message", exact: true }).click();
  const historyMessage = await until(async () => (await messages()).find((entry) => entry.sender === "owner" && entry.body.startsWith("@all")));
  assert.deepEqual(historyMessage.recipients, [leader.id]);
  assert.equal((await finished(historyMessage.id)).status, "succeeded");
  await expect(page.locator(".bot-badge").last()).toHaveText(leader.position);
  const assignment = await send(`delegate-worker-evidence: Delegate to agent ${worker.id} to read the exact file ${evidence}. Ask for the exact file marker and HISTORY_EMPTY if its supplied Recent group conversation is empty. Do not read the file yourself. After the worker finishes, give me its evidence in your summary.`);
  assert.equal((await request.post("/api/groups", { data: { ...group, scope_levels: [1, 2] } })).status(), 400);
  const summary = await until(async () => (await state()).runs.find((run) => run.message_id === assignment.id && run.kind === "summary" && !["queued", "starting", "running", "waiting"].includes(run.status)), 300000);
  assert.equal(summary.status, "succeeded", summary.error);
  const child = (await state()).runs.find((run) => run.message_id === assignment.id && run.kind === "delegate");
  assert.equal(child.agent_id, worker.id);
  assert.equal(child.status, "succeeded", child.error);
  assert(child.output.includes(marker) && child.output.includes("HISTORY_EMPTY"));
  assert(summary.output.includes(marker));
  assert(!child.organization_context.group_access.participant_ids.includes(worker.id));
  assert(child.organization_context.group_access.delegate_ids.includes(worker.id));
  assert(!(await messages()).some((entry) => entry.sender === worker.id || entry.run_id === child.id));
  assert((await messages()).some((entry) => entry.run_id === summary.id && entry.body.includes(marker)));
  const sessionRoot = path.join(org, ".state/runtime", worker.id, "codex/sessions");
  const files = (await readdir(sessionRoot, { recursive: true })).filter((file) => file.endsWith(".jsonl"));
  assert(files.length > 0);
  for (const file of files) assert(!(await readFile(path.join(sessionRoot, file), "utf8")).includes("BOARD_ONLY_HISTORY"), "Private worker must not receive prior board conversation");
  await page.reload();
  await expect(page.locator(".bot-badge").last()).toHaveText(leader.position);
  await page.screenshot({ path: path.join(directory, "group-position-badges.png"), animations: "disabled" });
  await page.getByRole("button", { name: "Manage group", exact: true }).click();
  dialog = page.getByRole("dialog", { name: "Manage group" });
  await expect(dialog.getByRole("checkbox", { name: "Level 1", exact: true })).toBeChecked();
  await dialog.getByRole("checkbox", { name: "Level 1", exact: true }).uncheck();
  await expect(dialog.getByRole("button", { name: "Save group", exact: true })).toBeDisabled();
  await dialog.getByRole("checkbox", { name: "Level 2", exact: true }).check();
  await expect(dialog.getByLabel("Group chat lead")).toHaveValue("");
  await dialog.getByRole("button", { name: "Save group", exact: true }).click();
  await expect(dialog).toBeHidden();
  group = (await state()).groups.find((entry) => entry.id === group.id);
  assert.deepEqual((await access()).participant_ids, [manager.id]);
  assert.equal((await access()).chat_lead_id, manager.id);
  assert(!(await access()).delegate_ids.includes(leader.id));
  assert((await call("/sessions", undefined, "GET")).filter((entry) => entry.group_id === group.id).every((entry) => !entry.active));
  const scheduled = await call(`/groups/${group.id}/schedules`, { name: "Scope route proof", body: "Reply exactly SCOPED_SCHEDULE_OK. Do not use tools or delegate.", start_at: new Date(Date.now() + 3000).toISOString(), repeat_minutes: null });
  const scheduledRun = await until(async () => {
    const current = (await state()).schedules.find((entry) => entry.id === scheduled.id);
    return current?.last_message_id && (await state()).runs.find((run) => run.message_id === current.last_message_id && run.status === "succeeded");
  }, 180000);
  assert.equal(scheduledRun.agent_id, manager.id);
  assert(scheduledRun.output.includes("SCOPED_SCHEDULE_OK"));
  group = await call("/groups", { ...group, scope_levels: [3], chat_lead_id: worker.id });
  const terminal = await call(`/agents/${manager.id}/terminal`, { id: crypto.randomUUID(), command: "Start-Sleep -Seconds 8; Write-Output 'SCOPE_QUEUE_RELEASE'" });
  const pending = await send("This must fail before starting after the hierarchy changes.");
  worker = await call(`/agents/${worker.id}`, { ...worker, reports_to: null }, "PUT");
  const denied = await finished(pending.id);
  assert.equal(denied.status, "failed");
  assert(denied.error.includes("outside this group's chat scope"));
  assert.equal(denied.pid, null);
  await until(async () => (await call(`/agents/${manager.id}/terminal/${terminal.id}`, undefined, "GET")).status === "completed", 20000);
  worker = await call(`/agents/${worker.id}`, { ...worker, reports_to: manager.id }, "PUT");
  group = await call("/groups", { ...group, scope_levels: [1], chat_lead_id: leader.id });
  await page.goto(groupUrl);
  await page.getByRole("button", { name: "Manage group", exact: true }).click();
  await page.setViewportSize({ width: 800, height: 900 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await expect(page.getByRole("checkbox", { name: "Level 1", exact: true })).toBeChecked();
  await page.screenshot({ path: path.join(directory, "group-scope-settings.png"), animations: "disabled" });
  for (const script of ["Stop", "Start"]) execFileSync("pwsh", ["-NoProfile", "-File", `../scripts/${script}.ps1`, "-Org", org], { stdio: "ignore", timeout: 25000 });
  assert.deepEqual((await access()).participant_ids, [leader.id]);
  assert(!(await messages()).some((entry) => entry.run_id === child.id));
  await page.reload();
  await page.getByRole("button", { name: "Manage group", exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "Level 1", exact: true })).toBeChecked();
  const proof = { group: group.id, participant: leader.id, delegatedWorker: child.agent_id, delegateRun: child.id, summaryRun: summary.id, marker, workerMessageCount: (await messages()).filter((entry) => entry.sender === worker.id).length, workerHistoryExcluded: true, scheduledLead: scheduledRun.agent_id, deniedQueuedRun: denied.id, restartPersisted: true, mocks: false };
  await writeFile(path.join(directory, "group-scope-proof.json"), JSON.stringify(proof, null, 2));
  return proof;
}
