import assert from "node:assert/strict";
import { copyFile, mkdir, writeFile, readFile, open, symlink, unlink } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { expect } from "@playwright/test";

export async function verifyMessageFiles({ page, request, call, state, until, finished, org, directory, base }) {
  assert(process.env.AE_TEST_ORG && path.resolve(org) !== path.resolve("../../org"), "Use a disposable organization");
  const initialGroup = (await state()).groups.find((item) => item.id === "general");
  if (initialGroup?.archived_at || initialGroup?.deleted_at) {
    await call("/groups/general/restore");
    await page.reload();
  }
  const root = path.join(org, `file viewer workdir ${Date.now()}`);
  const output = path.join(root, ".assistant");
  await mkdir(output, { recursive: true });
  const image = path.join(output, "screenshot # 日本語.png");
  const report = path.join(output, "report # 日本語.md");
  const reportText = `# Real file viewer check\n\nText is served from the attached workdir.\n\n| Item | Result |\n| --- | --- |\n| Rendering | Ready |\n\n\`\`\`text\nCODE_PREVIEW_OK\n\`\`\`\n\n![Evidence diagram](${encodeURIComponent(path.basename(image))})\n\n[Next report](next.md) · [Missing report](missing.md) · [Large report](large.md)\n\n<script>window.previewScriptExecuted = true</script>\n`;
  await copyFile("public/agentic-enterprise-logo.png", image);
  await writeFile(report, reportText);
  await writeFile(path.join(output, "next.md"), "# Next report\n\nNested Markdown links stay in this preview.\n");
  await writeFile(path.join(output, "empty.md"), "");
  await writeFile(path.join(output, "large.md"), "x".repeat(1024 * 1024 + 1));
  await writeFile(path.join(root, ".env"), "VIEWER_TEST_ONLY=not-a-secret\n");
  await writeFile(path.join(output, "active.html"), "<script>document.title='Do not execute'</script>");
  await writeFile(path.join(org, "outside.txt"), "Outside the attached workdir");
  const large = await open(path.join(output, "large.txt"), "w");
  await large.truncate(25 * 1024 * 1024 + 1);
  await large.close();
  const junction = path.join(root, "outside-junction");
  await symlink(org, junction, "junction");

  const workdir = (await call("/workspaces/probe", { path: root })).workspace;
  const original = (await state()).agents.find((agent) => agent.id === "ceo");
  const catalog = await call("/codex/settings", undefined, "GET");
  await call("/agents/ceo", { ...original, workdir, reasoning: "low",
    model: catalog.models.find((model) => model.slug === "gpt-5.6-luna")?.slug ?? catalog.model,
    instructions: "Return exactly the Markdown requested by the owner, without code fences, tools, commentary, or delegation." }, "PUT");
  const markdownPath = (file) => file.replaceAll("\\", "/").replaceAll("#", "%23");
  const markdown = `FILE_VIEWER_PROOF\n\n![Local screenshot](<${markdownPath(image)}>)\n\n[Open screenshot](<${markdownPath(image)}>) · [Read report](<${markdownPath(report)}>) · [Relative report](.assistant/report%20%23%20日本語.md) · [File URL](<${pathToFileURL(report).href}>) · [Website](https://example.com/proof)\n\n![Missing image](.assistant/missing.png)\n\n[Unsafe link](javascript:alert%281%29)`;
  await page.getByRole("textbox", { name: "Message", exact: true }).fill(`@${original.name} Return exactly this Markdown:\n\n${markdown}`);
  await page.getByRole("button", { name: "Send message", exact: true }).click();
  const owner = await until(async () => (await call("/groups/general/messages", undefined, "GET")).find((message) => message.sender === "owner" && message.body.includes(markdownPath(image))));
  const run = await finished(owner.id);
  assert.equal(run.status, "succeeded", run.error || run.output);
  const bubble = page.locator(".message-agent .message-bubble").filter({ has: page.locator(`img[src*="${run.id}"]`) });
  const picture = bubble.getByRole("link", { name: "Open image: Local screenshot", exact: true });
  await expect(picture).toBeVisible();
  await expect.poll(() => picture.evaluate((el) => el.naturalWidth)).toBeGreaterThan(0);
  const imageUrl = await picture.getAttribute("src");
  assert(imageUrl.startsWith(`/api/runs/${run.id}/files?`));
  const imageResponse = await request.get(imageUrl);
  assert.equal(imageResponse.status(), 200);
  assert.equal(imageResponse.headers()["content-type"], "image/png");
  assert.deepEqual(await imageResponse.body(), await readFile(image));
  await picture.focus();
  const openedImage = page.context().waitForEvent("page");
  await picture.press("Enter");
  const imageTab = await openedImage;
  await imageTab.waitForLoadState();
  await expect.poll(() => imageTab.locator("img").evaluate((el) => el.naturalWidth)).toBeGreaterThan(0);
  await imageTab.close();
  const reports = [];
  const preview = page.getByRole("complementary", { name: "Markdown preview" });
  const pageCount = page.context().pages().length;
  for (const label of ["Read report", "Relative report", "File URL"]) {
    const link = bubble.getByRole("link", { name: label, exact: true });
    const href = await link.getAttribute("href");
    const response = await request.get(href);
    assert.equal(response.status(), 200, await response.text());
    assert.equal(await response.text(), reportText);
    await link.click();
    await expect(preview.getByRole("heading", { name: "Real file viewer check" })).toBeVisible();
    await expect(preview.getByRole("cell", { name: "Ready" })).toBeVisible();
    await expect(preview.locator("pre")).toContainText("CODE_PREVIEW_OK");
    await expect.poll(() => preview.getByRole("link", { name: "Open image: Evidence diagram" }).evaluate((el) => el.naturalWidth)).toBeGreaterThan(0);
    assert.equal(page.context().pages().length, pageCount, "Markdown opens in the app, never a new tab");
    assert.equal(await page.evaluate(() => window.previewScriptExecuted), undefined, "Raw HTML does not execute");
    await page.getByRole("button", { name: "Close Markdown preview" }).press("Escape");
    await expect(preview).toHaveCount(0);
    await expect(link).toBeFocused();
    reports.push(label);
  }
  const readReport = bubble.getByRole("link", { name: "Read report", exact: true });
  const input = page.getByRole("textbox", { name: "Message", exact: true });
  await input.fill("Unsent draft stays while reading");
  await readReport.click();
  const width = (await preview.boundingBox()).width;
  const separator = page.getByRole("separator", { name: "Resize Markdown preview" });
  await separator.focus();
  await separator.press("ArrowLeft");
  await expect.poll(async () => (await preview.boundingBox()).width).not.toBe(width);
  await preview.getByRole("link", { name: "Next report", exact: true }).click();
  await expect(preview.getByRole("heading", { name: "Next report" })).toBeVisible();
  await readReport.click();
  await preview.getByRole("link", { name: "Missing report", exact: true }).click();
  await expect(preview.getByRole("alert")).not.toBeEmpty();
  await readReport.click();
  await preview.getByRole("link", { name: "Large report", exact: true }).click();
  await expect(preview.getByRole("alert")).toContainText("1 MiB preview limit");
  await expect(preview.getByRole("link", { name: "Download Markdown report" })).toBeVisible();
  await expect(input).toHaveValue("Unsent draft stays while reading");
  await input.fill("");
  await readReport.click();
  await page.setViewportSize({ width: 775, height: 900 });
  await expect(preview.getByRole("heading", { name: "Real file viewer check" })).toBeVisible();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  const titleBox = await page.locator(".group-title").boundingBox();
  const actionsBox = await page.locator(".topbar-actions").boundingBox();
  assert(titleBox.y + titleBox.height <= actionsBox.y || titleBox.x + titleBox.width <= actionsBox.x, "Chat title and controls do not overlap beside the preview");
  await page.screenshot({ path: path.join(directory, "markdown-preview-narrow.png"), animations: "disabled" });
  await page.getByRole("button", { name: "Close Markdown preview" }).click();
  await page.setViewportSize({ width: 1440, height: 980 });
  await expect(bubble.getByRole("link", { name: "Website", exact: true })).toHaveAttribute("href", "https://example.com/proof");
  await expect(bubble.getByRole("link", { name: "Website", exact: true })).toHaveAttribute("target", "_blank");
  await expect(bubble.getByRole("link", { name: "Unsafe link", exact: true })).toHaveCount(0);
  await expect(bubble.locator(".message-image-unavailable")).toContainText("Missing image — image unavailable");

  const url = (file) => `/api/runs/${run.id}/files?${new URLSearchParams({ path: file })}`;
  const denied = [".env", ".git/config", ".state/owner.key", "../outside.txt", path.join(org, "outside.txt"), "outside-junction/outside.txt", "report.md:stream", "//remote/share/image.png", "file://remote/share/image.png", ".assistant/missing.png", ".assistant", ".assistant/large.txt"];
  for (const file of denied) {
    const response = await request.get(url(file));
    assert.equal(response.status(), 400, file);
    assert((await response.json()).error, `Clear error for ${file}`);
  }
  await unlink(junction);
  const active = await request.get(url(".assistant/active.html"));
  assert.match(active.headers()["content-disposition"], /^attachment;/);
  assert.equal(active.headers()["content-type"], "application/octet-stream");
  assert.equal((await fetch(`${base}${imageUrl}`)).status, 401);
  assert.equal((await request.get(imageUrl, { headers: { Origin: "https://example.com" } })).status(), 403);

  await readReport.click();
  await preview.getByRole("button", { name: "Add to knowledge", exact: true }).click();
  await expect(preview.getByRole("button", { name: "Added to knowledge", exact: true })).toBeDisabled({ timeout: 180000 });
  await expect(preview.getByRole("status")).toContainText("Searchable in General.");
  const saved = (await state()).artifacts.find((item) => item.group_id === "general" && item.name === path.basename(report) && item.status === "indexed");
  assert(saved, "The real index reports success");
  assert.deepEqual(await (await request.get(`/api/artifacts/${saved.id}`)).body(), await readFile(report), "Knowledge stores the original Markdown bytes");
  const search = await call(`/search?semantic=true&group_id=general&q=${encodeURIComponent("file viewer rendering report")}`, undefined, "GET");
  assert(search.artifacts.some((item) => item.id === saved.id), "Saved report is returned by the real knowledge index");
  await page.getByRole("button", { name: "Close Markdown preview" }).click();
  await readReport.click();
  await preview.getByRole("button", { name: "Add to knowledge", exact: true }).click();
  await expect(preview.getByRole("button", { name: "Added to knowledge", exact: true })).toBeDisabled();
  assert.equal((await state()).artifacts.filter((item) => item.group_id === "general" && item.name === saved.name && item.status !== "deleted").length, 1, "Reopening and adding again reuses the saved copy");
  await page.screenshot({ path: path.join(directory, "report-added-to-knowledge.png"), animations: "disabled" });
  await page.getByRole("button", { name: "Knowledge", exact: true }).click();
  await page.reload();
  await expect(page.getByRole("row").filter({ hasText: saved.name })).toContainText("Searchable");
  const other = await call("/groups", { ...(await state()).groups.find((item) => item.id === "general"), id: "", name: `Other knowledge scope ${Date.now()}`, description: "Isolation check" });
  const otherSearch = await call(`/search?semantic=true&group_id=${other.id}&q=report`, undefined, "GET");
  assert.equal(otherSearch.artifacts.length, 0, "Reports stay in the selected group's knowledge");
  await page.goto("/groups/general/chat");
  await readReport.click();
  await preview.getByRole("link", { name: "Next report", exact: true }).click();
  // Use a real empty Markdown file to exercise indexing failure and retry.
  await page.getByRole("button", { name: "Close Markdown preview" }).click();
  await writeFile(report, `${reportText}\n\n[Empty report](empty.md)\n`);
  await readReport.click();
  await preview.getByRole("link", { name: "Empty report", exact: true }).click();
  await preview.getByRole("button", { name: "Add to knowledge", exact: true }).click();
  await expect(preview.getByRole("button", { name: "Retry indexing" })).toBeEnabled({ timeout: 30000 });
  await expect(preview.getByRole("alert")).toContainText("Document is empty");
  await preview.getByRole("button", { name: "Retry indexing" }).click();
  await expect(preview.getByRole("button", { name: "Retry indexing" })).toBeEnabled({ timeout: 30000 });
  await expect(preview.getByRole("alert")).toContainText("Document is empty");
  const emptyFiles = (await state()).artifacts.filter((item) => item.group_id === "general" && item.name === "empty.md" && item.status !== "deleted");
  assert.equal(emptyFiles.length, 1, "Index retry retains the saved empty file");
  assert.equal(emptyFiles[0].status, "failed");
  await writeFile(report, reportText);
  await call("/groups/general/archive");
  await page.reload();
  await readReport.click();
  await preview.getByRole("link", { name: "Next report", exact: true }).click();
  await expect(preview.getByRole("heading", { name: "Next report" })).toBeVisible();
  await expect(preview.getByRole("button", { name: "Add to knowledge", exact: true })).toBeDisabled();
  await expect(preview.getByRole("status")).toContainText("Restore this group");
  await call("/groups/general/restore");

  // A historical message keeps the run's workdir even after the profile moves.
  const moved = path.join(org, "new workdir");
  await mkdir(moved, { recursive: true });
  const current = (await state()).agents.find((agent) => agent.id === "ceo");
  await call("/agents/ceo", { ...current, workdir: (await call("/workspaces/probe", { path: moved })).workspace }, "PUT");
  await page.reload();
  await expect.poll(() => picture.evaluate((el) => el.naturalWidth)).toBeGreaterThan(0);
  await page.setViewportSize({ width: 775, height: 900 });
  assert(await picture.evaluate((el) => el.getBoundingClientRect().width <= el.parentElement.getBoundingClientRect().width));
  await page.screenshot({ path: path.join(directory, "message-files.png"), animations: "disabled" });
  return { runId: run.id, imageBytes: (await imageResponse.body()).length, reports, renderedPreview: true, previewNestedLinks: true, previewResize: true, previewFailureStates: true, noNewMarkdownTabs: true, knowledge: { artifactId: saved.id, sha256: saved.sha256, status: saved.status, semanticSearch: true, repeatedAddCount: 1, isolatedGroup: true, emptyRetryError: "Document is empty", archivedDisabled: true }, denied: denied.length, anonymous: 401, foreignOrigin: 403, historicalWorkdir: true, screenshot: path.join(directory, "message-files.png") };
}
