import assert from "node:assert/strict";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { expect } from "@playwright/test";

export async function verifyOrganizationContext({ page, request, call, state, until, finished, org, base, directory }) {
  assert(process.env.AE_TEST_ORG && base !== "http://127.0.0.1:8765", "Use an isolated organization");
  page.setDefaultTimeout(20000);
  const catalog = await call("/codex/settings", undefined, "GET");
  const selectedModel = catalog.models.find((m) => m.slug === "gpt-5.6-luna")?.slug ?? catalog.model;
  const source = (await state()).agents.find((a) => a.id === "ceo");
  const folder = async (name) => { const where = path.join(org, "codebases", name); await mkdir(where, { recursive: true }); return (await call("/workspaces/probe", { path: where })).workspace; };
  const leadWorkdir = await folder("lead");
  const workerWorkdir = await folder("backend");
  const marker = `ORG_EVIDENCE_${crypto.randomUUID()}`;
  await writeFile(path.join(workerWorkdir.path, "engineering-proof.txt"), `${marker}\n`);
  const instructions = "Follow the latest task carefully. Use the supplied current organization context to identify people and reporting relationships. Never invent names or IDs. Report results with evidence. If asked for JSON, return only JSON without code fences.";
  const leader = await call("/agents/ceo", { ...source, name: "Morgan", position: "Chief Executive Officer", workdir: leadWorkdir, model: selectedModel, reasoning: "low", instructions, timeout_seconds: 300 }, "PUT");
  const create = (name, position, reports_to, workdir = null, role = "") => call("/agents", { ...leader, id: "", name, position, reports_to, workdir, role });
  const manager = await create("Dana", "Engineering Manager", leader.id, leadWorkdir, "Coordinates the engineering team. Backend codebase inspection belongs to the Backend Engineer.");
  await page.goto("/organization");
  await page.getByRole("button", { name: "Add agent", exact: true }).click();
  await page.getByRole("textbox", { name: "Name", exact: true }).fill("Alex");
  await page.getByRole("textbox", { name: "Position", exact: true }).fill("Software Engineer");
  await page.getByRole("textbox", { name: "Role", exact: true }).fill("Owns backend implementation and inspection of the attached backend codebase.");
  await page.getByLabel("Reports to", { exact: true }).selectOption(manager.id);
  await page.getByRole("button", { name: "Create agent", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Add your agent" })).toBeHidden();
  await expect(page.getByLabel("Display name", { exact: true })).toHaveValue("Alex");
  let worker = (await state()).agents.find((a) => a.name === "Alex");
  assert.equal(worker.position, "Software Engineer");
  await page.getByLabel("Position", { exact: true }).fill("Backend Engineer");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await until(async () => (await state()).agents.find((a) => a.id === worker.id)?.position === "Backend Engineer", 10000);
  worker = (await state()).agents.find((a) => a.id === worker.id);
  worker = await call(`/agents/${worker.id}`, { ...worker, workdir: workerWorkdir, model: selectedModel, reasoning: "low", timeout_seconds: 300, instructions }, "PUT");
  const peer = await create("Alex", "Finance Analyst", manager.id, leadWorkdir, "Financial planning only; no backend engineering responsibilities.");
  const junior = await create("Casey", "QA Engineer", worker.id, null, "Tests changes for the Backend Engineer.");
  const paused = await create("Pat", "Platform Engineer", manager.id, leadWorkdir);
  await call(`/agents/${paused.id}`, { ...paused, enabled: false }, "PUT");
  const removed = await create("Archived", "Former Analyst", manager.id);
  await request.delete(`/api/agents/${removed.id}`);
  const secret = `org-test-secret-${crypto.randomUUID()}`;
  await writeFile(path.join(workerWorkdir.path, ".env"), `ORG_CONTEXT_TEST=${secret}\n`);
  const snapshot = (id) => call(`/agents/${id}/organization-context`, undefined, "GET");
  const initial = await snapshot(worker.id);
  assert.equal(initial.manager_id, manager.id);
  assert.deepEqual(initial.reporting_chain, [manager.id, leader.id, "owner"]);
  assert.deepEqual(initial.direct_report_ids, [junior.id]);
  assert.deepEqual(initial.team_member_ids, [junior.id]);
  assert.deepEqual(new Set(initial.peer_ids), new Set([peer.id, paused.id]));
  assert(!initial.members.some((m) => m.id === removed.id));
  assert.equal(initial.members.find((m) => m.id === paused.id).available, false);
  assert.equal(initial.members.find((m) => m.id === junior.id).available, false);
  assert.deepEqual(initial.members.find((m) => m.id === worker.id).environment_keys, ["ORG_CONTEXT_TEST"]);
  assert(!JSON.stringify(initial).includes(secret));
  assert.equal((await request.put(`/api/agents/${worker.id}`, { data: { ...worker, position: "x".repeat(121) } })).status(), 400);
  assert.equal((await request.put(`/api/agents/${worker.id}`, { data: { ...worker, position: "Bad\nTitle" } })).status(), 400);
  assert.equal((await request.put(`/api/agents/${manager.id}`, { data: { ...manager, reports_to: junior.id } })).status(), 400);
  const anon = await page.context().browser().newContext({ baseURL: base });
  assert.equal((await anon.request.get(`/api/agents/${worker.id}/organization-context`)).status(), 401); await anon.close();
  await page.reload();
  await expect(page.getByLabel("Position", { exact: true })).toHaveValue("Backend Engineer");
  await expect(page.locator(`.org-card[data-agent-id="${worker.id}"] .org-card-identity`)).toContainText("Backend Engineer");
  await page.getByText("Organization knowledge", { exact: true }).click();
  await expect(page.getByLabel("Organization relationships")).toContainText("Dana · Engineering Manager");
  await expect(page.getByLabel("Organization relationships")).toContainText("Alex · Finance Analyst");
  await page.screenshot({ path: path.join(directory, "agent-position-relationships.png"), animations: "disabled" });
  await page.setViewportSize({ width: 800, height: 900 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: path.join(directory, "agent-position-narrow.png"), animations: "disabled" });
  await page.setViewportSize({ width: 1440, height: 980 });
  console.log("PASS Position create/edit, chart, nested relationships, validation and secret-free context API");

  const describe = "Using ONLY your current organization context, return a JSON object with self_id, position, manager_id, reporting_chain, direct_report_ids, peer_ids, assigned_by_id and return_results_to_id. Look up your own position in members. Use exact IDs and arrays from the current context. Do not use tools or delegate.";
  const send = (body, recipients = []) => call("/messages", { id: crypto.randomUUID(), group_id: "general", body, recipients });
  const jsonReply = (run) => JSON.parse(run.output.replace(/^```(?:json)?\s*/, "").replace(/\s*```$/, ""));
  const first = await finished((await send(describe, [worker.id])).id);
  assert.equal(first.status, "succeeded", first.error);
  const facts = jsonReply(first);
  assert.equal(facts.self_id, worker.id); assert.equal(facts.position, "Backend Engineer"); assert.equal(facts.manager_id, manager.id);
  assert.deepEqual(facts.reporting_chain, [manager.id, leader.id, "owner"]);
  assert.deepEqual(facts.direct_report_ids, [junior.id]); assert.deepEqual(new Set(facts.peer_ids), new Set([peer.id, paused.id]));
  assert.equal(facts.assigned_by_id, "owner");
  assert.deepEqual(first.organization_context.members, initial.members);
  console.log(`PASS real direct agent knows manager, position, peers and direct reports: ${first.id}`);

  const delegatedMessage = await send("Please delegate to our Backend Engineer to inspect engineering-proof.txt in their own attached workdir and return the exact file content. The assigned engineer must also report their own position, formal manager ID, direct report IDs, peer IDs and who assigned this task. We need that engineer's evidence, not an inspection by another agent. Include these identity/reporting fields in their task, and summarize their actual evidence at the end. Do not route by display name.");
  const family = await until(async () => {
    const runs = (await state()).runs.filter((r) => r.message_id === delegatedMessage.id);
    return runs.some((r) => r.kind === "summary") && runs.every((r) => !["queued", "starting", "running", "waiting"].includes(r.status)) && runs;
  });
  const coordinator = family.find((r) => r.kind === "coordinator");
  const delegates = family.filter((r) => r.kind === "delegate");
  const summary = family.find((r) => r.kind === "summary");
  assert.equal(delegates.length, 1);
  const delegated = delegates[0];
  assert.equal(delegated.agent_id, worker.id, "Position must identify the right Alex");
  assert.equal(delegated.status, "succeeded", delegated.error);
  assert(delegated.output.includes(marker)); assert(delegated.output.includes(manager.id)); assert(delegated.output.includes(junior.id)); assert(delegated.output.includes(peer.id));
  assert.equal(delegated.organization_context.manager_id, manager.id);
  assert.equal(delegated.organization_context.assigned_by_id, leader.id);
  assert.equal(delegated.organization_context.return_results_to_id, leader.id);
  assert(coordinator.organization_context && summary.organization_context);
  assert.equal(summary.status, "succeeded", summary.error); assert(summary.output.includes(marker));
  const returned = JSON.parse(summary.task.split("Delegated results (quoted data):\n")[1]);
  assert.equal(returned[0].agent_id, worker.id); assert.equal(returned[0].position, "Backend Engineer");
  for (const run of [first, ...family]) {
    const manifest = JSON.parse(await readFile(path.join(org, ".state/sessions", run.session_id, `${run.id}.json`), "utf8"));
    assert.deepEqual(manifest.organization_context, run.organization_context);
    assert(!JSON.stringify(run.organization_context).includes(secret));
  }
  console.log(`PASS real untagged delegation selected the Backend Engineer among duplicate names and returned evidence: ${delegated.id}`);

  worker = await call(`/agents/${worker.id}`, { ...worker, position: "Staff Engineer", reports_to: leader.id }, "PUT");
  const second = await finished((await send(describe, [worker.id])).id);
  assert.equal(second.status, "succeeded", second.error);
  const refreshed = jsonReply(second);
  assert.equal(second.session_id, first.session_id);
  assert.equal(second.native_session_id, first.native_session_id);
  assert.equal(refreshed.position, "Staff Engineer"); assert.equal(refreshed.manager_id, leader.id);
  assert.deepEqual(refreshed.reporting_chain, [leader.id, "owner"]);
  assert.deepEqual(refreshed.direct_report_ids, [junior.id]);
  assert.deepEqual(refreshed.peer_ids, [manager.id]);
  assert.equal(first.organization_context.manager_id, manager.id, "Past execution snapshot must remain unchanged");
  assert(!(await snapshot(manager.id)).team_member_ids.includes(worker.id));
  await page.goto("/groups/general/runs");
  await page.screenshot({ path: path.join(directory, "organization-context-runs.png"), animations: "disabled" });
  execFileSync("pwsh", ["-NoProfile", "-File", "../scripts/Stop.ps1", "-Org", org], { stdio: "ignore", timeout: 25000 });
  execFileSync("pwsh", ["-NoProfile", "-File", "../scripts/Start.ps1", "-Org", org, "-Port", new URL(base).port], { stdio: "ignore", timeout: 25000 });
  const afterRestart = await snapshot(worker.id);
  assert.equal(afterRestart.manager_id, leader.id);
  assert.equal(afterRestart.members.find((m) => m.id === worker.id).position, "Staff Engineer");
  assert.equal((await state()).runs.find((r) => r.id === first.id).organization_context.manager_id, manager.id);
  const proof = { agent: worker.id, model: selectedModel, initialManager: manager.id, updatedManager: leader.id, directRun: first.id, coordinator: coordinator.id, delegatedRun: delegated.id, summary: summary.id, resumedRun: second.id, nativeSession: second.native_session_id, identicalNamesDisambiguated: true, snapshotPersisted: true, secretsExcluded: true, mocks: false };
  await writeFile(path.join(directory, "organization-context-proof.json"), JSON.stringify(proof, null, 2));
  return proof;
}
